### ISSUE TITLE
Loading with 32 threads per warp but feeding less than 32 threads.

### ISSUE THREAD

**Issue by YohannDudouit** [bryancatanzaro/trove#10]
Hi,

I am working at warp level to use __shfl__ intrinsics but I sometimes end up using less than 32 threads per warp. Since the bottleneck of my GPU Kernels is always the bandwidth, I was wondering if it is possible to use Trove to load the 2D data with 32 threads but distribute it to a smaller number of threads.

Thank you in advance for your help,
Sincerely,
Yohann

**Comment by bryancatanzaro** [comment]
I don't know how to do this with Trove directly. It's possible that there's something similar to Trove that could do this, but deriving how to do it might be complex. I would start with using CUDA shared memory to do the load with more threads, and distribute the data to the threads you're using.

**Comment by bryancatanzaro** [comment]
(Closing because I don't have time to add this feature, but please send a PR if you figure something out)
