### ISSUE TITLE
compiler warnings with CUDA 9

### ISSUE THREAD

**Issue by samuelpmish** [bryancatanzaro/trove#8]
First, thanks so much for making this library! It's been a huge performance win for a lot of my kernels. Recently, I'm seeing a handful of warnings (from the CUDA 9 changes to __ballot(), __shfl(), etc.) when compiling projects with Trove. Is it feasible to update these calls appropriately, or would that break compatibility with older versions of nvcc?

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by bryancatanzaro** [comment]
It should be easy to fix this. There's just a few places with __shfl(), and
they'd need to be redone with __shfl_sync(), and the call to __ballot()
should be replaced with an __activemask() call.

Try it out and send in a PR if you have time.
